In [2]:
#Chargement des données

%matplotlib inline
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
import warnings; warnings.simplefilter('ignore')

data= pd.read_excel(r"C:\Users\ccraq\OneDrive\Documents\PYTHON\projet_python\dataset.xlsx")
data

,id,imdb_id,popularity,budget,revenue,original_title,cast,homepage,director,tagline,...,overview,runtime,genres,production_companies,release_date,vote_count,vote_average,release_year,budget_adj,revenue_adj
0,135397,tt0369610,32.985763,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,http://www.jurassicworld.com/,Colin Trevorrow,The park is open.,...,Twenty-two years after the events of Jurassic ...,124.0,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,2015-09-06 00:00:00,5562.0,6.5,2015.0,1.379999e+08,1.392446e+09
1,76341,tt1392190,28.419936,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,http://www.madmaxmovie.com/,George Miller,What a Lovely Day.,...,An apocalyptic story set in the furthest reach...,120.0,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,5/13/2015,6185.0,7.1,2015.0,1.379999e+08,3.481613e+08
2,262500,tt2908446,13.112507,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,http://www.thedivergentseries.movie/#insurgent,Robert Schwentke,One Choice Can Destroy You,...,Beatrice Prior must confront her inner demons ...,119.0,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,3/18/2015,2480.0,6.3,2015.0,1.012000e+08,2.716190e+08
3,140607,tt2488496,11.173104,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,http://www.starwars.com/films/star-wars-episod...,J.J. Abrams,Every generation has a story.,...,Thirty years after defeating the Galactic Empi...,136.0,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,12/15/2015,5292.0,7.5,2015.0,1.839999e+08,1.902723e+09
4,168259,tt2820852,9.335014,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,http://www.furious7.com/,James Wan,Vengeance Hits Home,...,Deckard Shaw seeks revenge against Dominic Tor...,137.0,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2015-01-04 00:00:00,2947.0,7.3,2015.0,1.747999e+08,1.385749e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10873,21,tt0060371,0.080598,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,NaN,Bruce Brown,NaN,...,"The Endless Summer, by Bruce Brown, is one of ...",95.0,Documentary,Bruce Brown Films,6/15/1966,11.0,7.4,1966.0,0.000000e+00,0.000000e+00
10874,20379,tt0060472,0.065543,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,NaN,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,...,Grand Prix driver Pete Aron is fired by his te...,176.0,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,12/21/1966,20.0,5.7,1966.0,0.000000e+00,0.000000e+00
10875,39768,tt0060161,0.065141,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,NaN,Eldar Ryazanov,NaN,...,An insurance agent who moonlights as a carthie...,94.0,Mystery|Comedy,Mosfilm,1966-01-01 00:00:00,11.0,6.5,1966.0,0.000000e+00,0.000000e+00
10876,21449,tt0061177,0.064317,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,NaN,Woody Allen,WOODY ALLEN STRIKES BACK!,...,"In comic Woody Allen's film debut, he took the...",80.0,Action|Comedy,Benedict Pictures Corp.,1966-02-11 00:00:00,22.0,5.4,1966.0,0.000000e+00,0.000000e+00
10877,22293,tt0060666,0.035919,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,NaN,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,...,A family gets lost on the road and stumbles up...,74.0,Horror,Norm-Iris,11/15/1966,15.0,1.5,1966.0,1.276423e+05,0.000000e+00

In [3]:
#Traitement des données: on enlève les colonnes que l'on ne souhaite pas exploiter 
data = data.drop(columns=['imdb_id','popularity','homepage','release_date','budget_adj','revenue_adj'])
data

,id,budget,revenue,original_title,cast,director,tagline,keywords,overview,runtime,genres,production_companies,vote_count,vote_average,release_year
0,135397,150000000,1513528810,Jurassic World,Chris Pratt|Bryce Dallas Howard|Irrfan Khan|Vi...,Colin Trevorrow,The park is open.,monster|dna|tyrannosaurus rex|velociraptor|island,Twenty-two years after the events of Jurassic ...,124.0,Action|Adventure|Science Fiction|Thriller,Universal Studios|Amblin Entertainment|Legenda...,5562.0,6.5,2015.0
1,76341,150000000,378436354,Mad Max: Fury Road,Tom Hardy|Charlize Theron|Hugh Keays-Byrne|Nic...,George Miller,What a Lovely Day.,future|chase|post-apocalyptic|dystopia|australia,An apocalyptic story set in the furthest reach...,120.0,Action|Adventure|Science Fiction|Thriller,Village Roadshow Pictures|Kennedy Miller Produ...,6185.0,7.1,2015.0
2,262500,110000000,295238201,Insurgent,Shailene Woodley|Theo James|Kate Winslet|Ansel...,Robert Schwentke,One Choice Can Destroy You,based on novel|revolution|dystopia|sequel|dyst...,Beatrice Prior must confront her inner demons ...,119.0,Adventure|Science Fiction|Thriller,Summit Entertainment|Mandeville Films|Red Wago...,2480.0,6.3,2015.0
3,140607,200000000,2068178225,Star Wars: The Force Awakens,Harrison Ford|Mark Hamill|Carrie Fisher|Adam D...,J.J. Abrams,Every generation has a story.,android|spaceship|jedi|space opera|3d,Thirty years after defeating the Galactic Empi...,136.0,Action|Adventure|Science Fiction|Fantasy,Lucasfilm|Truenorth Productions|Bad Robot,5292.0,7.5,2015.0
4,168259,190000000,1506249360,Furious 7,Vin Diesel|Paul Walker|Jason Statham|Michelle ...,James Wan,Vengeance Hits Home,car race|speed|revenge|suspense|car,Deckard Shaw seeks revenge against Dominic Tor...,137.0,Action|Crime|Thriller,Universal Pictures|Original Film|Media Rights ...,2947.0,7.3,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10873,21,0,0,The Endless Summer,Michael Hynson|Robert August|Lord 'Tally Ho' B...,Bruce Brown,NaN,surfer|surfboard|surfing,"The Endless Summer, by Bruce Brown, is one of ...",95.0,Documentary,Bruce Brown Films,11.0,7.4,1966.0
10874,20379,0,0,Grand Prix,James Garner|Eva Marie Saint|Yves Montand|Tosh...,John Frankenheimer,Cinerama sweeps YOU into a drama of speed and ...,car race|racing|formula 1,Grand Prix driver Pete Aron is fired by his te...,176.0,Action|Adventure|Drama,Cherokee Productions|Joel Productions|Douglas ...,20.0,5.7,1966.0
10875,39768,0,0,Beregis Avtomobilya,Innokentiy Smoktunovskiy|Oleg Efremov|Georgi Z...,Eldar Ryazanov,NaN,car|trolley|stealing car,An insurance agent who moonlights as a carthie...,94.0,Mystery|Comedy,Mosfilm,11.0,6.5,1966.0
10876,21449,0,0,"What's Up, Tiger Lily?",Tatsuya Mihashi|Akiko Wakabayashi|Mie Hama|Joh...,Woody Allen,WOODY ALLEN STRIKES BACK!,spoof,"In comic Woody Allen's film debut, he took the...",80.0,Action|Comedy,Benedict Pictures Corp.,22.0,5.4,1966.0
10877,22293,19000,0,Manos: The Hands of Fate,Harold P. Warren|Tom Neyman|John Reynolds|Dian...,Harold P. Warren,It's Shocking! It's Beyond Your Imagination!,fire|gun|drive|sacrifice|flashlight,A family gets lost on the road and stumbles up...,74.0,Horror,Norm-Iris,15.0,1.5,1966.0

In [5]:
#Pour pouvoir proposer des films parmi les mieux notés dans leurs catégories on va calculer les notes pondérées par nombre de votes pour enlever les films qui ont très peu de notes
#On crée un dataframe avec les deux colonnes qui nous intéressent et on enlève les valeurs non disponibles
votes_data=data.loc[:,['vote_average','vote_count']]

votes_data.dropna(inplace=True)

In [7]:
#On vérifie qu'il n'y a plus de valeurs indisponibles et on regarde l'aspect du dataframe
votes_data.isna().sum()
votes_data

       vote_average  vote_count
0               6.5      5562.0
1               7.1      6185.0
2               6.3      2480.0
3               7.5      5292.0
4               7.3      2947.0
...             ...         ...
10873           7.4        11.0
10874           5.7        20.0
10875           6.5        11.0
10876           5.4        22.0
10877           1.5        15.0

[10506 rows x 2 columns]

In [13]:
vote_counts= votes_data['vote_count']
vote_averages = votes_data['vote_average']

#On calcule la moyenne des notes de tout les films

mean_votes=vote_averages.mean()
mean_votes

5.974300399771582

In [12]:
#Pour être inclus il faut que le film ait plus de notes que 95% des films de la liste
#On calcule alors le minimum de notes a avoir

minimum=vote_counts.quantile(0.8)
minimum

#J'ai choisi le quantile 0.8 et non 0.95 car sinon il restait très peu de films
#Donc ici il faut que le film ait au moins 207 notes

207.0

In [15]:
#On va maintenant combien de films se qualifient parmi ces critères

data['year'] = pd.to_datetime(data['release_year'], errors='coerce').apply(lambda x: str(x).split('-')[0] if x != np.nan else np.nan)

#Donc ici on ne va prendre en compte que les films qui ont au minimum 207 notes et qui n'ont pas de valeur nulles

qualified = data[(data['vote_count'] >= minimum) & (data['vote_count'].notnull()) & (data['vote_average'].notnull())][['original_title', 'year', 'vote_count', 'vote_average', 'genres']]
qualified['vote_count'] = qualified['vote_count'].astype('int')
qualified['vote_average'] = qualified['vote_average'].astype('int')
qualified.shape

#On voit que 2102 films correpondent à notre critère

(2102, 5)

In [19]:
#Ici on va calculer la moyenne pondérée 

def moyenne_pondérée(x):
    c = x['vote_count']
    a = x['vote_average']
    return (c/(c+minimum) * a) + (minimum/(minimum+c) * mean_votes)

qualified['mp'] = qualified.apply(weighted_rating, axis=1)
qualified = qualified.sort_values('mp', ascending=False).head(250)

#Ici on choisit d'avoir les 250 films avec les meilleurs films
 
qualified.head(10)

#Là on a les 10 films les mieux notés toutes catégories qui rentrent dans les critères que l'on a définit plus haut

,original_title,year,vote_count,vote_average,genres,mp
2877,The Dark Knight,1970,8432,8,Drama|Action|Crime|Thriller,7.951462
630,Interstellar,1970,6498,8,Adventure|Drama|Science Fiction,7.937462
2411,Fight Club,1970,5923,8,Drama,7.931595
4184,The Shawshank Redemption,1970,5754,8,Drama|Crime,7.929656
4183,Pulp Fiction,1970,5343,8,Thriller|Crime,7.924447
4185,Forrest Gump,1970,4856,8,Comedy|Drama|Romance,7.917180
7276,The Godfather,1970,3970,8,Drama|Crime,7.899612
7316,The Empire Strikes Back,1970,3954,8,Adventure|Action|Science Fiction,7.899226
9,Inside Out,1970,3935,8,Comedy|Animation|Family,7.898764
637,The Imitation Game,1970,3478,8,History|Drama|Thriller|War,7.886209

In [29]:
#Maintenant on classe selon les genres

def build_chart(genre, percentile=0.7):
    dg = gen_data[gen_data['genre'] == genre]
    vote_counts = dg[dg['vote_count'].notnull()]['vote_count'].astype('int')
    vote_averages = dg[dg['vote_average'].notnull()]['vote_average'].astype('int')
    mean_votes= vote_averages.mean()
    minimum = vote_counts.quantile(percentile)
    
    qualified = dg[(dg['vote_count'] >= minimum) & (dg['vote_count'].notnull()) & (dg['vote_average'].notnull())][['original_title', 'year', 'vote_count', 'vote_average']]
    qualified['vote_count'] = qualified['vote_count'].astype('int')
    qualified['vote_average'] = qualified['vote_average'].astype('int')
    
    qualified['mp'] = qualified.apply(lambda x: (x['vote_count']/(x['vote_count']+minimum) * x['vote_average']) + (minimum/(minimum+x['vote_count']) * mean_votes), axis=1)
    qualified = qualified.sort_values('mp', ascending=False).head(250)
    
    return qualified

In [31]:
#Ici on voit les films d'action les mieux notés
build_chart('Action').head(10)

,original_title,year,vote_count,vote_average,mp
25,Mission: Impossible - Rogue Nation,1970,2349,7,6.932067
6688,The Guardian,1970,212,7,6.447999
4995,Once Upon a Time in Mexico,1970,320,6,5.809647
1458,State of Play,1970,257,6,5.774877
6267,The Interpreter,1970,197,6,5.727466
9467,Bloodsport,1970,180,6,5.710172
7595,Pathfinder,1970,92,5,5.057004
4552,So Undercover,1970,169,5,5.039918
6320,Stealth,1970,195,5,5.036250
4491,The Man with the Iron Fists,1970,244,5,5.030898